name: Tests
on: [push, workflow_dispatch]
jobs:
  build:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Add files
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: dep-cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/puppeteer
          key: tests-dependencies-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Build files
        run: npm run build
      - name: Run tests
        run: npm run test:all